services:
  jenkins-agent:
    image: fm39hz/docker-in-jenkins:agent-latest
    container_name: jenkins-agent
    volumes:
      - /home/${USER}/${PROJECT}:/home/jenkins/agent/${PROJECT}
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}
    ports:
      - "2222:22"
    restart: unless-stopped
    user: root
